### PR TITLE
Bumped sgx_tstd to v1.0.9

### PR DESCRIPTION
**Pull request by tomtau**

### CODE REVIEW

**Comment by dingelish** [comment]
no worry! I'll batch on these forked crate tomorrow!

**Comment by dingelish** [comment]
too tired today 😂

**Comment by tomtau** [comment]
OK

**Comment by dingelish** [comment]
you can use a `patch` section to patch the global dependency like [this](https://github.com/baidu/rust-sgx-sdk/blob/master/samplecode/hello-rust/enclave/Cargo.toml#L16)
or if you use xargo, simply update Xargo.toml and everything will be fine

**Pull request closed without merging**
